---
title: "Getting Started with teal.modules.general"
author: "NEST"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started with teal.modules.general}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Introduction

`teal` is a package that extends the `shiny` framework to build interactive GUI applications using the R programming 
language. `shiny`, and hence `teal`, is implemented to allow the building of large applications by combining small,
decoupled modules. `teal.modules.general` is a package consisting of a set of modules that are used to build `teal`
applications. It is "general" in the sense that the intended functions of these modules are more fundamental. This is
in contrast to the intended functions of its sister package, `teal.modules.clinical`, which is more specialized around
clinical data.

See [`teal.modules.clinical's README`](https://github.com/insightsengineering/teal.modules.clinical).

### Main features

There are five areas of data science that `teal.modules.general` provides tools and solutions (modules) for, namely:
* viewing data in tabular form - `tm_variable_browser`, `tm_data_table`, `tm_t_crosstable`
* visualizing data in plots and graphs - `tm_g_scatterplot`, `tm_g_association`, `tm_g_bivariate`, `tm_g_response`, etc.
* examining missing and extreme values in data - `tm_missing_data`, `tm_outliers`
* performing data analysis - `tm_a_pca`, `tm_g_distribution`, `tm_a_regression`
* viewing data and files in a directory - `tm_file_viewer`

### Example application

```{r, eval=FALSE}
# a package that contains the data that will be used in this example
library(scda)
# calling library(shiny) is not needed because teal already depends on it
# calling library(teal) is not needed because teal.modules.general already depends on it

# the two datasets from the scda package that will be used in this example 
ADSL <- synthetic_cdisc_data("latest")$adsl
ADTTE <- synthetic_cdisc_data("latest")$adtte

# init, cdisc_data, cdisc_dataset, and modules are functions from teal
app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", x = ADSL, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
    cdisc_dataset("ADTTE", x = ADTTE, code = "ADTTE <- synthetic_cdisc_data(\"latest\")$adtte"),
    check = TRUE # to check if the code executes to the data provided, x, i.e. ADSL and ADTTE
  ),
  modules(
    # a function / module from teal.modules.general that will display the two scda datasets in tabular form
    # when this shiny / teal app is run
    tm_variable_browser(
      # a name to display in the GUI
      label = "Variable browser",
      # this argument takes a set of arguments to pass to ggplot2.
      # the arguments must have the same name as its ggplot2 counterpart, e.g. `subtitle`
      ggplot2_args = teal.devel::ggplot2_args(labs = list(subtitle = "Plot generated by Variable Browser Module")),
    )
  )
)

# the above app only contains one module, tm_variable_browser. 
# however, a teal app is generalized to have arbitrary many modules.
# simply add the modules one after another inside of the `modules` function to create a larger teal app.

# shiny function to initialize the shiny / teal app created above
shinyApp(app$ui, app$server)
```
