---
title: "Getting started teal.modules.general"
author: "NEST"
date: "03.03.2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started teal.modules.general}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Introduction

`teal` is a package that extends the `shiny` framework to build interactive GUI applications using the R programming
language. `shiny`, and hence `teal`, is implemented to allow the building of large applications by combining small,
decoupled modules. `teal.modules.general` is a package consisting of a set of modules that are used to build `teal`
applications. It is "general" in the sense that the intended functions of these modules are more fundamental. This is
in contrast to the intended functions of its sister package, `teal.modules.clinical`, which is more specialized around
clinical data. The modules of `teal.modules.general` can be combined with modules of `teal.modules.clinical` and / or
other `shiny` modules to build a large `teal` / `shiny` app.

See [`teal's README`](https://github.com/insightsengineering/teal).
See [`teal.modules.clinical's README`](https://github.com/insightsengineering/teal.modules.clinical).

### Main features

There are five areas of data science that `teal.modules.general` provides tools and solutions (modules) for:
* viewing data in tabular form
* visualizing data in plots and graphs
* examining missing and extreme values in data
* performing data analysis
* viewing data and files in a directory

See [package functions / modules`](https://insightsengineering.github.io/teal.modules.general/reference/index.html).

### Example application

```{r, eval = FALSE}
# a package that contains the data that will be used in this example
library(scda)
# calling library(shiny) is not needed because teal already depends on it
# calling library(teal) is not needed because teal.modules.general already depends on it

# the two datasets from the scda package that will be used in this example
ADSL <- synthetic_cdisc_data("latest")$adsl # nolint
ADTTE <- synthetic_cdisc_data("latest")$adtte # nolint

# init, cdisc_data, cdisc_dataset, and modules are functions from teal
app <- init(
  data = cdisc_data(
    # raw datasets need to be converted to datasets consumed by teal.
    # cdisc_dataset is a teal function that does that.
    # a set of datasets is converted to a block of data to be managed in one place.
    # cdisc_data is a teal function that does that.
    cdisc_dataset("ADSL", x = ADSL, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
    cdisc_dataset("ADTTE", x = ADTTE, code = "ADTTE <- synthetic_cdisc_data(\"latest\")$adtte"),
    check = TRUE # to check if the code executes to the data provided, x, i.e. ADSL and ADTTE
  ),
  modules(
    # a function / module from teal.modules.general that will display the two scda datasets in tabular form
    # when this shiny / teal app is run
    tm_variable_browser(
      # a name to display in the GUI
      label = "Variable browser",
      # this argument takes a set of arguments to pass to ggplot2.
      # the arguments must have the same names as its ggplot2 counterpart, e.g. `subtitle`
      ggplot2_args = teal.devel::ggplot2_args(labs = list(subtitle = "Plot generated by Variable Browser Module")),
    )
  )
)

# the above app only contains one module, tm_variable_browser.
# however, a teal app is generalized to have arbitrary many modules.
# one way to build a larger app is to list the modules one after another inside of the `modules` function.

# shiny function to initialize the shiny / teal app created above
shinyApp(app$ui, app$server)
```
