---
title: "Using scatterplot matrix"
author: "Dawid Kałędkowski"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
runtime: shiny
vignette: >
  %\VignetteIndexEntry{Scatterplot matrix examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r echo=TRUE, message=FALSE, warning=FALSE, results="hide"}
library(teal.modules.general)
library(random.cdisc.data)
library(dplyr)
ADSL <- cadsl
ADSL_2 <- cadsl
ADRS <- cadrs
ADTTE <- cadtte
ADLB <- cadlb %>%
  mutate(CHGC = as.factor(case_when(
    CHG < 1 ~ "N",
    CHG > 1 ~ "P",
    TRUE ~ "-"
  )))

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL),
    dataset("ADSL_2", ADSL_2, keys = get_cdisc_keys("ADSL")),
    cdisc_dataset("ADRS", ADRS),
    cdisc_dataset("ADTTE", ADTTE),
    cdisc_dataset("ADLB", ADLB),
    code = "ADSL <- cadsl
            ADSL_2 <- cadsl
            ADRS <- cadrs
            ADTTE <- cadtte
            ADLB <- cadlb %>%
            mutate(CHGC = as.factor(case_when(
            CHG < 1 ~ 'N',
            CHG > 1 ~ 'P',
            TRUE ~ '-'
            )))",
    check = TRUE
  ),
  modules = root_modules(
    modules(
        label = "Scatterplot matrix",
      # .. single wide ----
      tm_g_scatterplotmatrix(
        label = "Single wide dataset",
        variables = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variables:",
            choices = colnames(ADSL),
            selected = c("AGE", "RACE", "SEX", "BMRKR1", "BMRKR2"),
            multiple = TRUE,
            fixed = FALSE
          )
        )
      ),

      tm_g_scatterplotmatrix(
        label = "Multiple wide datasets",
        variables = list(
          data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              label = "Select variables:",
              choices = colnames(ADSL),
              selected = c("AGE", "ACTARM", "SEX", "BMRKR1"),
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          data_extract_spec(
            dataname = "ADSL_2",
            select = select_spec(
              label = "Select variables:",
              choices = colnames(ADSL_2),
              selected = c("COUNTRY", "ACTARM", "STRATA1"),
              multiple = TRUE,
              fixed = FALSE
            )
          )
        )
      ),

      tm_g_scatterplotmatrix(
        "One long dataset",
        variables = data_extract_spec(
          dataname = "ADTTE",
          select = select_spec(
            choices = c("AVAL", "BMRKR1", "BMRKR2"),
            selected = c("AVAL", "BMRKR1", "BMRKR2"),
            multiple = TRUE,
            fixed = FALSE,
            label = "Select variables:"
          )
        )
      ),

      tm_g_scatterplotmatrix(
        label = "Two long datasets",
        variables = list(
          data_extract_spec(
            dataname = "ADRS",
            select = select_spec(
              label = "Select variables:",
              choices = names(ADRS),
              selected = c("AVAL", "AVALC"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              label = "Select endpoints:",
              vars = c("PARAMCD", "AVISIT"),
              choices = apply(as.matrix(expand.grid(
                levels(ADRS$PARAMCD), levels(ADRS$AVISIT))), 1, paste, collapse = " - "),
              selected = "OVRINV - SCREENING",
              multiple = FALSE
            )
          ),
          data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              label = "Select variables:",
              choices = names(ADTTE),
              selected = c("AVAL", "CNSR"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              label = "Select parameters:",
              vars = "PARAMCD",
              choices = levels(ADTTE$PARAMCD),
              selected = "OS",
              multiple = TRUE
            )
          )
        )
      )
    )
  )
)
      
```


```{r echo=FALSE}
shinyApp(app$ui, app$server, options = list(height = 1024, width = 1024))
```
