---
title: "Using bivariate plot"
author: "Dawid Kałędkowski"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
runtime: shiny
vignette: >
  %\VignetteIndexEntry{Bivariate plot examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r echo=TRUE, message=FALSE, warning=FALSE, results="hide"}
library(teal.modules.general)
library(random.cdisc.data)
library(dplyr)
ADSL <- cadsl
ADSL_2 <- cadsl
ADRS <- cadrs
ADTTE <- cadtte
ADLB <- cadlb %>%
  mutate(CHGC = as.factor(case_when(
    CHG < 1 ~ "N",
    CHG > 1 ~ "P",
    TRUE ~ "-"
  )))

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL),
    dataset("ADSL_2", ADSL_2, keys = get_cdisc_keys("ADSL")),
    cdisc_dataset("ADRS", ADRS),
    cdisc_dataset("ADTTE", ADTTE),
    cdisc_dataset("ADLB", ADLB),
    code = "ADSL <- cadsl
            ADSL_2 <- cadsl
            ADRS <- cadrs
            ADTTE <- cadtte
            ADLB <- cadlb %>%
            mutate(CHGC = as.factor(case_when(
            CHG < 1 ~ 'N',
            CHG > 1 ~ 'P',
            TRUE ~ '-'
            )))",
    check = TRUE
  ),
  modules = root_modules(
    # tm_g_bivariate ------
    modules(
      label = "Bivariate plot",
      tm_g_bivariate(
        label = "Single wide dataset",
        x = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variable:",
            choices = names(ADSL),
            selected = "BMRKR1",
            fixed = FALSE
          )
        ),
        y = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variable:",
            choices = names(ADSL),
            selected = "SEX",
            multiple = FALSE,
            fixed = FALSE
          )
        ),
        row_facet = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variables:",
            choices = names(ADSL),
            selected = NULL,
            multiple = TRUE,
            fixed = FALSE
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variables:",
            choices = names(ADSL),
            selected = NULL,
            multiple = TRUE,
            fixed = FALSE
          )
        )
      ),

      tm_g_bivariate(
        label = "Two wide datasets",
        x = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variable:",
            choices = c("BMRKR1", "AGE", "SEX", "STRATA1", "RACE"),
            selected = c("BMRKR1"),
            multiple = FALSE
          )
        ),
        y = data_extract_spec(
          dataname = "ADSL_2",
          select = select_spec(
            label = "Select variables:",
            choices = c("COUNTRY", "AGE", "RACE"),
            selected = "RACE",
            multiple = FALSE
          )
        ),
        row_facet = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variable:",
            choices = names(ADSL),
            selected = NULL,
            multiple = FALSE,
            fixed = FALSE
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADSL_2",
          select = select_spec(
            label = "Select variables:",
            choices = names(ADSL),
            selected = NULL,
            multiple = TRUE,
            fixed = FALSE
          )
        )
      ),

      tm_g_bivariate(
        label = "Multiple different long datasets",
        x = data_extract_spec(
          dataname = "ADRS",
          filter = filter_spec(
            label = "Select endpoints:",
            vars = c("PARAMCD", "AVISIT"),
            choices = apply(as.matrix(expand.grid(levels(ADRS$PARAMCD), levels(ADRS$AVISIT))),
                            1, paste, collapse = " - "),
            selected = "OVRINV - END OF INDUCTION",
            multiple = TRUE
          ),
          select = select_spec(
            choices = c("AVALC", "AVAL"),
            selected = "AVALC",
            multiple = FALSE
          )
        ),
        y = data_extract_spec(
          dataname = "ADTTE",
          select = select_spec(
            label = "Select variable:",
            choices = c("AVAL", "CNSR"),
            selected = "AVAL",
            multiple = FALSE,
            fixed = FALSE
          ),
          filter = filter_spec(
            label = "Select endpoint:",
            vars = c("PARAMCD"),
            choices = levels(ADTTE$PARAMCD),
            selected = "OS",
            multiple = FALSE
          )
        ),
        row_facet = data_extract_spec(
          dataname = "ADRS",
          filter = filter_spec(
            label = "Select endpoints:",
            vars = c("PARAMCD", "AVISIT"),
            choices = apply(as.matrix(expand.grid(levels(ADRS$PARAMCD), levels(ADRS$AVISIT))),
                            1, paste, collapse = " - "),
            selected = "OVRINV - SCREENING",
            multiple = TRUE
          ),
          select = select_spec(
            label = "Select variable:",
            choices = c("SEX", "RACE", "COUNTRY", "ARM", "PARAMCD", "AVISIT"),
            selected = "SEX",
            multiple = FALSE,
            fixed = FALSE
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variables:",
            choices = c("SEX", "RACE"),
            selected = NULL,
            multiple = TRUE,
            fixed = FALSE
          )
        ),
        expert_settings = TRUE,
        plot_height = c(600, 200, 2000),
        ggtheme = "grey"
      ),

      tm_g_bivariate(
        label = "Wide and long datasets",
        x = data_extract_spec(
          dataname = "ADRS",
          filter = list(
            filter_spec(
              vars = "PARAM",
              choices = levels(ADRS$PARAM),
              selected = levels(ADRS$PARAM)[2],
              multiple = FALSE,
              label = "Select response:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADRS$AVISIT),
              selected = levels(ADRS$AVISIT)[2],
              multiple = FALSE,
              label = "Select visit:"
            )
          ),
          select = select_spec(
            choices = c("AVALC", "AVAL"),
            selected = "AVALC",
            multiple = FALSE,
            label = "Select variable:"
          )
        ),
        y = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            choices = c("BMRKR1", "SEX", "AGE", "RACE", "COUNTRY"),
            selected = "BMRKR1",
            multiple = FALSE,
            label = "Select variable:",
            fixed = FALSE
          )
        ),
        row_facet = data_extract_spec(
          dataname = "ADRS",
          select = select_spec(
            choices = c("SEX", "RACE", "ARMCD", "PARAMCD"),
            selected = "SEX",
            multiple = FALSE,
            label = "Select variable:"
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADRS",
          select = select_spec(
            choices = c("SEX", "RACE", "ARMCD", "PARAMCD", "AVISIT"),
            selected = "ARMCD",
            multiple = FALSE,
            fixed = FALSE,
            label = "Select variable:"
          )
        )
      ),

      tm_g_bivariate(
        label = "Wide and multiple long datasets",
        x = data_extract_spec(
          dataname = "ADRS",
          filter = list(
            filter_spec(
              vars = "PARAMCD",
              choices = levels(ADRS$PARAMCD),
              selected = levels(ADRS$PARAMCD)[2],
              multiple = FALSE,
              label = "Select response:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADRS$AVISIT),
              selected = levels(ADRS$AVISIT)[2],
              multiple = FALSE,
              label = "Select visit:"
            )
          ),
          select = select_spec(
            choices = c("AVALC", "AVAL"),
            selected = "AVALC",
            multiple = FALSE,
            label = "Select variable:"
          )
        ),
        y = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            choices = c("BMRKR1", "SEX", "AGE", "RACE", "COUNTRY"),
            selected = "BMRKR1",
            multiple = FALSE,
            fixed = FALSE
          )
        ),
        row_facet = data_extract_spec(
          dataname = "ADLB",
          filter = list(
            filter_spec(
              vars = "PARAM",
              choices = levels(ADLB$PARAM),
              selected = levels(ADLB$PARAM)[1],
              multiple = FALSE,
              label = "Select measurement:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADLB$AVISIT),
              selected = levels(ADLB$AVISIT)[1],
              multiple = FALSE,
              label = "Select visit:"
            )
          ),
          select = select_spec(
            choices = "ARMCD",
            selected = NULL,
            multiple = FALSE,
            fixed = FALSE,
            label = "Select variable:"
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            choices = c("SEX", "AGE", "RACE", "COUNTRY"),
            selected = NULL,
            multiple = FALSE,
            fixed = FALSE,
            label = "Select variable:"
          )
        ),
        expert_settings = TRUE,
        plot_height = c(600, 200, 2000),
        ggtheme = "grey"
      ),

      tm_g_bivariate(
        label = "Same long datasets (same subset)",
        x = data_extract_spec(
          dataname = "ADRS",
          select = select_spec(
            choices = c("AVALC", "AVAL"),
            selected = "AVALC",
            multiple = FALSE,
            fixed = FALSE,
            label = "Select variable:"
          )
        ),
        y = data_extract_spec(
          dataname = "ADRS",
          select = select_spec(
            choices = c("SEX", "RACE", "COUNTRY", "ARMCD", "BMRKR1", "BMRKR2"),
            selected = "BMRKR1",
            multiple = FALSE,
            fixed = FALSE,
            label = "Select variable:"
          )
        ),
        row_facet = data_extract_spec(
          dataname = "ADRS",
          select = select_spec(
            choices = c("AVISIT", "PARAMCD"),
            selected = "PARAMCD",
            multiple = TRUE,
            label = "Select variables:"
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADRS",
          select = select_spec(
            choices = c("AVISIT", "PARAMCD"),
            selected = "AVISIT",
            multiple = TRUE,
            label = "Select variables:"
          )
        )
      ),

      tm_g_bivariate(
        label = "Same datasets (different subsets)",
        x = data_extract_spec(
          dataname = "ADLB",
          filter = list(
            filter_spec(
              vars = "PARAMCD",
              choices = levels(ADLB$PARAMCD),
              selected = levels(ADLB$PARAMCD)[1],
              multiple = FALSE,
              label = "Select lab:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADLB$AVISIT),
              selected = levels(ADLB$AVISIT)[2],
              multiple = FALSE,
              label = "Select visit:"
            )
          ),
          select = select_spec(
            choices = "AVAL",
            selected = "AVAL",
            multiple = FALSE,
            fixed = TRUE
          )
        ),
        y = data_extract_spec(
          dataname = "ADLB",
          filter = list(
            filter_spec(
              vars = "PARAMCD",
              choices = levels(ADLB$PARAMCD),
              selected = levels(ADLB$PARAMCD)[1],
              multiple = FALSE,
              label = "Select lab:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADLB$AVISIT),
              selected = levels(ADLB$AVISIT)[1],
              multiple = FALSE,
              label = "Select visit:"
            )
          ),
          select = select_spec(
            choices = "AVAL",
            selected = "AVAL",
            multiple = FALSE,
            fixed = TRUE
          )
        ),
        use_density = FALSE,
        row_facet = data_extract_spec(
          dataname = "ADLB",
          filter = list(
            filter_spec(
              vars = "PARAMCD",
              choices = levels(ADLB$PARAMCD),
              selected = levels(ADLB$PARAMCD)[1],
              multiple = FALSE,
              label = "Select lab:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADLB$AVISIT),
              selected = levels(ADLB$AVISIT)[1],
              multiple = FALSE,
              label = "Select category:"
            )
          ),
          select = select_spec(
            choices = c("RACE", "SEX", "ARMCD", "ACTARMCD"),
            selected = NULL,
            multiple = TRUE,
            fixed = FALSE,
            label = "Select variable:"
          )
        ),
        col_facet = data_extract_spec(
          dataname = "ADLB",
          filter = list(
            filter_spec(
              vars = "PARAMCD",
              choices = levels(ADLB$PARAMCD),
              selected = levels(ADLB$PARAMCD)[1],
              multiple = FALSE,
              label = "Select lab:"
            ),
            filter_spec(
              vars = "AVISIT",
              choices = levels(ADLB$AVISIT),
              selected = levels(ADLB$AVISIT)[3],
              multiple = FALSE,
              label = "Select category:"
            )
          ),
          select = select_spec(
            choices = c("RACE", "SEX", "ARMCD", "ACTARMCD"),
            selected = "ARMCD",
            multiple = TRUE,
            fixed = FALSE,
            label = "Select variables:"
          )
        ),
        expert_settings = TRUE,
        plot_height = c(600, 200, 2000),
        ggtheme = "grey"
      )
    )
  )
)
```


```{r echo=FALSE}
shinyApp(app$ui, app$server, options = list(height = 1024, width = 1024))
```
