testthat::test_that("tm_g_bivariate creates a `teal_module` object", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_s3_class(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      row_facet = mock_data_extract_spec(select_multiple = FALSE),
      col_facet = mock_data_extract_spec(select_multiple = FALSE),
      facet = TRUE,
      color_setting = TRUE,
      use_density = TRUE,
      free_x_scales = TRUE,
      free_y_scales = TRUE,
      plot_height = c(400, 100, 600),
      plot_width = c(600, 100, 600),
      rotate_xaxis_labels = TRUE,
      swap_axes = TRUE
    ),
    "teal_module"
  )
})

testthat::test_that("tm_g_bivariate creates a `teal_module` object with default options", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_s3_class(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE)
    ),
    "teal_module"
  )
})

testthat::test_that("tm_g_bivariate creates a `teal_module` object with multiple data extract specs", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_s3_class(
    tm_g_bivariate(
      "a label",
      list(mock_data_extract_spec(select_multiple = FALSE), mock_data_extract_spec(select_multiple = FALSE)),
      list(mock_data_extract_spec(select_multiple = FALSE), mock_data_extract_spec(select_multiple = FALSE)),
      plot_height = c(400, 100, 600),
      plot_width = c(600, 100, 600)
    ),
    "teal_module"
  )
})

testthat::test_that("tm_g_bivariate creates a module with `ui_args` that have all arguments of function", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  mod <- tm_g_bivariate(
    "a label",
    mock_data_extract_spec(select_multiple = FALSE),
    mock_data_extract_spec(select_multiple = FALSE)
  )

  testthat::expect_contains(
    names(mod$ui_args),
    names(formals(tm_g_bivariate))
  )
})

testthat::test_that("tm_g_bivariate creates a module with `ui_args` that have all arguments of function", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  mod <- tm_g_bivariate(
    "a label",
    list(
      mock_data_extract_spec(dataname = "A", select_multiple = FALSE),
      mock_data_extract_spec(dataname = "B", select_multiple = FALSE)
    ),
    mock_data_extract_spec(dataname = "C", select_multiple = FALSE)
  )

  expect_setequal(
    mod$datanames,
    c("A", "B", "C")
  )
})

testthat::test_that("tm_g_bivariate module UI function creates a shiny tag", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  mod <- tm_g_bivariate(
    "a label",
    mock_data_extract_spec(select_multiple = FALSE),
    mock_data_extract_spec(select_multiple = FALSE)
  )

  testthat::expect_class(
    do.call(
      mod$ui,
      c(list("a_id"), mod$ui_args)
    ),
    "shiny.tag"
  )
})

testthat::test_that("tm_g_bivariate module server", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  data <- teal_data()
  data <- within(data, {
    require(nestcolor)
    CO2 <- data.frame(CO2)
  })
  datanames(data) <- c("CO2")
  join_keys(data) <- default_cdisc_join_keys[datanames(data)]

  mod <- tm_g_bivariate(
    x = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "conc",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    y = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "uptake",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    row_facet = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "Type",
        fixed = FALSE
      )
    ),
    col_facet = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "Treatment",
        fixed = FALSE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Bivariate Module")
    )
  )

  shiny::testServer(
    mod$server,
    args = c(mod$server_args, data = shiny::reactive(data)),
    expr = {
      checkmate::expect_data_frame(
        anl_merged_q()[["ANL"]],
        min.rows = 1
      )
    }
  )
})

# Test `x` and `y` arguments with invalid data_extract_spec

testthat::test_that("tm_g_bivariate fails when `x` contains a spec with multiple selection", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      list(
        mock_data_extract_spec(select_multiple = TRUE)
      ),
      list()
    ),
    "'x' should not allow multiple selection"
  )
})

testthat::test_that("tm_g_bivariate fails when `x` contains multiple spec with (at least one ) multiple selection", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      list(
        mock_data_extract_spec(select_multiple = FALSE),
        mock_data_extract_spec(select_multiple = TRUE)
      ),
      list(mock_data_extract_spec(select_multiple = FALSE))
    ),
    "'x' should not allow multiple selection"
  )
})

testthat::test_that("tm_g_bivariate fails when `x` contains multiple spec with (at least one ) multiple selection", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      list(
        mock_data_extract_spec(select_multiple = FALSE),
        mock_data_extract_spec(select_multiple = TRUE)
      )
    ),
    "'y' should not allow multiple selection"
  )
})

testthat::test_that("tm_g_bivariate fails when `y` contains multiple spec with (at least one ) multiple selection", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      list(
        mock_data_extract_spec(select_multiple = FALSE),
        mock_data_extract_spec(select_multiple = TRUE)
      )
    ),
    "'y' should not allow multiple selection"
  )
})

# Test `plot_height` and `plot_width` arguments

testthat::test_that("tm_g_bivariate fails when `plot_height` is not valid", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      plot_height = c(100, 10, 20)
    ),
    "Assertion on 'plot_height' failed: Element 1 is not <= 20"
  )
})

testthat::test_that("tm_g_bivariate fails when `plot_height` is not valid", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      plot_height = c(1, 10, 20)
    ),
    "Assertion on 'plot_height' failed: Element 1 is not >= 10"
  )
})

testthat::test_that("tm_g_bivariate fails when `plot_height` is not valid", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      plot_height = 100
    ),
    "Assertion on 'plot_height' failed: Must have length 3, but has length 1"
  )
})

testthat::test_that("tm_g_bivariate fails when `plot_width` is not valid", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      plot_width = c(100, 10, 20)
    ),
    "Assertion on 'plot_width' failed: Element 1 is not <= 20"
  )
})

testthat::test_that("tm_g_bivariate fails when `plot_width` is not valid", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      plot_width = c(1, 10, 20)
    ),
    "Assertion on 'plot_width' failed: Element 1 is not >= 10"
  )
})

testthat::test_that("tm_g_bivariate fails when `plot_width` is not valid", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      plot_width = 100
    ),
    "Assertion on 'plot_width' failed: Must have length 3, but has length 1"
  )
})

# Test `color_settings` argument

testthat::test_that("tm_g_bivariate fails when `color_setting` is FALSE and `color` is supplied", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      color_setting = FALSE,
      color = mock_data_extract_spec()
    ),
    "'color_settings' argument needs to be set to TRUE if 'color', 'fill', and/or 'size' is/are supplied."
  )
})

testthat::test_that("tm_g_bivariate fails when `color_setting` is FALSE and `size` is supplied", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      color_setting = FALSE,
      size = mock_data_extract_spec()
    ),
    "'color_settings' argument needs to be set to TRUE if 'color', 'fill', and/or 'size' is/are supplied."
  )
})

testthat::test_that("tm_g_bivariate fails when `color_setting` is FALSE and `fill` is supplied", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  testthat::expect_error(
    tm_g_bivariate(
      "a label",
      mock_data_extract_spec(select_multiple = FALSE),
      mock_data_extract_spec(select_multiple = FALSE),
      color_setting = FALSE,
      fill = mock_data_extract_spec()
    ),
    "'color_settings' argument needs to be set to TRUE if 'color', 'fill', and/or 'size' is/are supplied."
  )
})

testthat::test_that("tm_g_bivariate determines `color`, `size` and `fill` when `color_setting` is TRUE", {
  local_logger_threshold(logger::FATAL) # Suppress logger messages

  mod <- tm_g_bivariate(
    "a label",
    mock_data_extract_spec(select_multiple = FALSE),
    mock_data_extract_spec(select_multiple = FALSE),
    color_setting = TRUE
  )

  testthat::expect_contains(
    vapply(
      unlist(mod$ui_args[c("color", "size", "fill")], recursive = FALSE),
      class,
      character(1)
    ),
    "data_extract_spec"
  )
})
