app_driver_tm_g_distribution <- function() {
  data <- teal.data::teal_data()
  data <- within(data, {
    ADSL <- rADSL
  })
  teal.data::datanames(data) <- c("ADSL")
  teal.data::join_keys(data) <- teal.data::default_cdisc_join_keys[teal.data::datanames(data)]

  vars1 <- teal.transform::choices_selected(
    teal.transform::variable_choices(data[["ADSL"]], c("ARM", "COUNTRY", "SEX")),
    selected = NULL
  )

  TealAppDriver$new(
    data = data,
    modules = teal::modules(
      tm_g_distribution(
        dist_var = teal.transform::data_extract_spec(
          dataname = "ADSL",
          select = teal.transform::select_spec(
            choices = teal.transform::variable_choices(data[["ADSL"]], c("AGE", "BMRKR1")),
            selected = "BMRKR1",
            multiple = FALSE,
            fixed = FALSE
          )
        ),
        strata_var = teal.transform::data_extract_spec(
          dataname = "ADSL",
          filter = teal.transform::filter_spec(
            vars = vars1,
            multiple = TRUE
          )
        ),
        group_var = teal.transform::data_extract_spec(
          dataname = "ADSL",
          filter = teal.transform::filter_spec(
            vars = vars1,
            multiple = TRUE
          )
        ),
        ggplot2_args = teal.widgets::ggplot2_args(
          labs = list(subtitle = "Plot generated by Distribution Module")
        )
      )
    )
  )
}

testthat::test_that("e2e - tm_g_distribution: module is initialised with the specified defaults", {
  skip_if_too_deep(5)

  app <- app_driver_tm_g_distribution()

  app$expect_no_shiny_error()

  # Encodings in the Histogram tab
  testthat::expect_equal(app$get_active_module_input("dist_i-dataset_ADSL_singleextract-select"), "BMRKR1")
  testthat::expect_null(app$get_active_module_input("group_i-dataset_ADSL_singleextract-filter1-col"))
  testthat::expect_null(app$get_active_module_input("group_i-dataset_ADSL_singleextract-filter1-vals"))
  testthat::expect_null(app$get_active_module_input("strata_i-dataset_ADSL_singleextract-filter1-col"))
  testthat::expect_equal(app$get_active_module_input("bins"), 30)
  testthat::expect_equal(app$get_active_module_input("main_type"), "Density")
  testthat::expect_true(app$get_active_module_input("add_dens"))
  testthat::expect_null(app$get_active_module_input("t_dist"))
  testthat::expect_identical(app$get_active_module_input("dist_param1"), NA)
  testthat::expect_identical(app$get_active_module_input("dist_param2"), NA)
  testthat::expect_null(app$get_active_module_input("dist_tests"))
  testthat::expect_equal(app$get_active_module_input("roundn"), 2)
  testthat::expect_equal(app$get_active_module_input("ggtheme"), "gray")
  testthat::expect_equal(app$get_active_module_input("tabs"), "Histogram")

  # Encodings in the QQplot tab
  app$set_module_input("tabs", "QQplot")
  testthat::expect_true(app$get_active_module_input("qq_line"))

  app$stop()
})
